"""Deterministic 10 CPU + 10 GPU sample for Sprint 18B.

Covers diverse manufacturers, naming conventions, and edge cases
(missing fields, malformed values, invisible characters).
"""

SAMPLE_CPUS: list[dict[str, str]] = [
    {
        "name": "AMD Ryzen 5 5600",
        "manufacturer": "AMD",
        "cores": "6",
        "threads": "12",
        "base_clock": "3.5 GHz",
        "boost_clock": "4.4 GHz",
        "tdp": "65 W",
        "socket": "AM4",
        "release_date": "2022-04-04",
    },
    {
        "name": "Intel Core i5-12400F",
        "manufacturer": "Intel",
        "cores": "6",
        "threads": "12",
        "base_clock": "2.5 GHz",
        "boost_clock": "4.4 GHz",
        "tdp": "65 W",
        "socket": "LGA1700",
        "release_date": "2022-01-04",
    },
    {
        "name": "AMD Ryzen 9 5950X",
        "manufacturer": "AMD",
        "cores": "16",
        "threads": "32",
        "base_clock": "3.4 GHz",
        "boost_clock": "4.9 GHz",
        "tdp": "105 W",
        "socket": "AM4",
        "release_date": "2020-11-05",
    },
    {
        "name": "Intel Core i9-13900K",
        "manufacturer": "Intel",
        "cores": "24",
        "threads": "32",
        "base_clock": "3.0 GHz",
        "boost_clock": "5.8 GHz",
        "tdp": "125 W",
        "socket": "LGA1700",
        "release_date": "2022-10-20",
    },
    {
        "name": "Apple M1",
        "manufacturer": "Apple",
        "cores": "8",
        "threads": "8",
        "base_clock": "3.2 GHz",
        "boost_clock": "",
        "tdp": "",
        "socket": "",
        "release_date": "2020-11-17",
    },
    {
        "name": "AMD EPYC 7763",
        "manufacturer": "AMD",
        "cores": "64",
        "threads": "128",
        "base_clock": "2.45 GHz",
        "boost_clock": "3.5 GHz",
        "tdp": "280 W",
        "socket": "SP3",
        "release_date": "2022-03-28",
    },
    {
        "name": "Intel Xeon E5-2680 v4",
        "manufacturer": "Intel",
        "cores": "14",
        "threads": "28",
        "base_clock": "2.4 GHz",
        "boost_clock": "3.3 GHz",
        "tdp": "120 W",
        "socket": "LGA2011-3",
        "release_date": "2016-02-01",
    },
    {
        "name": "AMD Ryzen 7 5800X3D",
        "manufacturer": "AMD",
        "cores": "8",
        "threads": "16",
        "base_clock": "3.4 GHz",
        "boost_clock": "4.5 GHz",
        "tdp": "105 W",
        "socket": "AM4",
        "release_date": "2022-04-20",
    },
    {
        "name": "Intel Core i7-12700K",
        "manufacturer": "Intel",
        "cores": "12",
        "threads": "20",
        "base_clock": "3.6 GHz",
        "boost_clock": "5.0 GHz",
        "tdp": "125 W",
        "socket": "LGA1700",
        "release_date": "2021-11-04",
    },
    {
        "name": "Qualcomm Snapdragon 8 Gen 2",
        "manufacturer": "Qualcomm",
        "cores": "8",
        "threads": "8",
        "base_clock": "2.0 GHz",
        "boost_clock": "3.2 GHz",
        "tdp": "",
        "socket": "",
        "release_date": "2022-11-15",
    },
]

SAMPLE_GPUS: list[dict[str, str]] = [
    {
        "name": "NVIDIA GeForce RTX 5090",
        "manufacturer": "NVIDIA",
        "memory_gb": "32 GB",
        "memory_type": "GDDR7",
        "core_clock": "2010 MHz",
        "boost_clock": "2407 MHz",
        "tdp": "575 W",
        "interface": "PCIe 5.0 x16",
        "length_mm": "304 mm",
        "release_date": "2025-01-30",
    },
    {
        "name": "NVIDIA GeForce RTX 4090",
        "manufacturer": "NVIDIA",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6X",
        "core_clock": "2235 MHz",
        "boost_clock": "2520 MHz",
        "tdp": "450 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "336 mm",
        "release_date": "2022-10-12",
    },
    {
        "name": "AMD Radeon RX 7900 XTX",
        "manufacturer": "AMD",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6",
        "core_clock": "1855 MHz",
        "boost_clock": "2499 MHz",
        "tdp": "355 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "287 mm",
        "release_date": "2022-12-13",
    },
    {
        "name": "Intel Arc B580",
        "manufacturer": "Intel",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "1945 MHz",
        "boost_clock": "2670 MHz",
        "tdp": "190 W",
        "interface": "PCIe 4.0 x8",
        "length_mm": "272 mm",
        "release_date": "2024-12-13",
    },
    {
        "name": "NVIDIA GeForce RTX 3060",
        "manufacturer": "NVIDIA",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "1320 MHz",
        "boost_clock": "1777 MHz",
        "tdp": "170 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "242 mm",
        "release_date": "2021-02-25",
    },
    {
        "name": "AMD Radeon RX 6700 XT",
        "manufacturer": "AMD",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "2321 MHz",
        "boost_clock": "2581 MHz",
        "tdp": "230 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "267 mm",
        "release_date": "2021-03-18",
    },
    {
        "name": "NVIDIA GeForce GTX 1080 Ti",
        "manufacturer": "NVIDIA",
        "memory_gb": "11 GB",
        "memory_type": "GDDR5X",
        "core_clock": "1480 MHz",
        "boost_clock": "1582 MHz",
        "tdp": "250 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "267 mm",
        "release_date": "2017-03-10",
    },
    {
        "name": "AMD Radeon RX 580",
        "manufacturer": "AMD",
        "memory_gb": "8 GB",
        "memory_type": "GDDR5",
        "core_clock": "1257 MHz",
        "boost_clock": "1340 MHz",
        "tdp": "185 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "256 mm",
        "release_date": "2017-04-18",
    },
    {
        "name": "NVIDIA Quadro RTX 6000",
        "manufacturer": "NVIDIA",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6",
        "core_clock": "1440 MHz",
        "boost_clock": "1770 MHz",
        "tdp": "260 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "267 mm",
        "release_date": "2018-08-13",
    },
    {
        "name": "AMD Radeon Pro W6800",
        "manufacturer": "AMD",
        "memory_gb": "32 GB",
        "memory_type": "GDDR6",
        "core_clock": "1979 MHz",
        "boost_clock": "2320 MHz",
        "tdp": "250 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "267 mm",
        "release_date": "2021-06-21",
    },
]

EDGE_CASE_CPUS: list[dict[str, str]] = [
    {
        "name": "AMD Ryzen 5 5600\u00a0",
        "manufacturer": "AMD",
        "cores": "6",
        "threads": "12",
        "base_clock": "3.5 GHz",
        "boost_clock": "4.4 GHz",
        "tdp": "65 W",
        "socket": "AM4",
        "release_date": "2022-04-04",
    },
    {
        "name": "Intel Core i5-12400F",
        "manufacturer": "Intel",
        "cores": "6",
        "threads": "12",
        "base_clock": "2.5 GHz",
        "boost_clock": "4.4 GHz",
        "tdp": "65 W",
        "socket": "LGA1700",
        "release_date": "2022-01-04",
    },
    {
        "name": "AMD Ryzen 9 5950X",
        "manufacturer": "AMD",
        "cores": "16",
        "threads": "32",
        "base_clock": "3.4 GHz",
        "boost_clock": "4.9 GHz",
        "tdp": "105 W",
        "socket": "AM4",
        "release_date": "2020-11-05",
    },
    {
        "name": "Intel Core i9-13900K",
        "manufacturer": "Intel",
        "cores": "24",
        "threads": "32",
        "base_clock": "3.0 GHz",
        "boost_clock": "5.8 GHz",
        "tdp": "125 W",
        "socket": "LGA1700",
        "release_date": "2022-10-20",
    },
    {
        "name": "Apple M1",
        "manufacturer": "Apple",
        "cores": "8",
        "threads": "8",
        "base_clock": "3.2 GHz",
        "boost_clock": "",
        "tdp": "",
        "socket": "",
        "release_date": "2020-11-17",
    },
    {
        "name": "AMD EPYC 7763",
        "manufacturer": "AMD",
        "cores": "64",
        "threads": "128",
        "base_clock": "2.45 GHz",
        "boost_clock": "3.5 GHz",
        "tdp": "280 W",
        "socket": "SP3",
        "release_date": "2022-03-28",
    },
    {
        "name": "Intel Xeon E5-2680 v4",
        "manufacturer": "Intel",
        "cores": "14",
        "threads": "28",
        "base_clock": "2.4 GHz",
        "boost_clock": "3.3 GHz",
        "tdp": "120 W",
        "socket": "LGA2011-3",
        "release_date": "2016-02-01",
    },
    {
        "name": "AMD Ryzen 7 5800X3D",
        "manufacturer": "AMD",
        "cores": "8",
        "threads": "16",
        "base_clock": "3.4 GHz",
        "boost_clock": "4.5 GHz",
        "tdp": "105 W",
        "socket": "AM4",
        "release_date": "2022-04-20",
    },
    {
        "name": "Intel Core i7-12700K",
        "manufacturer": "Intel",
        "cores": "12",
        "threads": "20",
        "base_clock": "3.6 GHz",
        "boost_clock": "5.0 GHz",
        "tdp": "125 W",
        "socket": "LGA1700",
        "release_date": "2021-11-04",
    },
    {
        "name": "Qualcomm Snapdragon 8 Gen 2",
        "manufacturer": "Qualcomm",
        "cores": "8",
        "threads": "8",
        "base_clock": "2.0 GHz",
        "boost_clock": "3.2 GHz",
        "tdp": "",
        "socket": "",
        "release_date": "2022-11-15",
    },
]

EDGE_CASE_GPUS: list[dict[str, str]] = [
    {
        "name": "NVIDIA GeForce RTX 5090",
        "manufacturer": "NVIDIA",
        "memory_gb": "32 GB",
        "memory_type": "GDDR7",
        "core_clock": "2010 MHz",
        "boost_clock": "2407 MHz",
        "tdp": "575 W",
        "interface": "PCIe 5.0 x16",
        "length_mm": "304 mm",
        "release_date": "2025-01-30",
    },
    {
        "name": "NVIDIA GeForce RTX 4090",
        "manufacturer": "NVIDIA",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6X",
        "core_clock": "2235 MHz",
        "boost_clock": "2520 MHz",
        "tdp": "450 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "336 mm",
        "release_date": "2022-10-12",
    },
    {
        "name": "AMD Radeon RX 7900 XTX",
        "manufacturer": "AMD",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6",
        "core_clock": "1855 MHz",
        "boost_clock": "2499 MHz",
        "tdp": "355 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "287 mm",
        "release_date": "2022-12-13",
    },
    {
        "name": "Intel Arc B580",
        "manufacturer": "Intel",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "1945 MHz",
        "boost_clock": "2670 MHz",
        "tdp": "190 W",
        "interface": "PCIe 4.0 x8",
        "length_mm": "272 mm",
        "release_date": "2024-12-13",
    },
    {
        "name": "NVIDIA GeForce RTX 3060",
        "manufacturer": "NVIDIA",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "1320 MHz",
        "boost_clock": "1777 MHz",
        "tdp": "170 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "242 mm",
        "release_date": "2021-02-25",
    },
    {
        "name": "AMD Radeon RX 6700 XT",
        "manufacturer": "AMD",
        "memory_gb": "12 GB",
        "memory_type": "GDDR6",
        "core_clock": "2321 MHz",
        "boost_clock": "2581 MHz",
        "tdp": "230 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "267 mm",
        "release_date": "2021-03-18",
    },
    {
        "name": "NVIDIA GeForce GTX 1080 Ti",
        "manufacturer": "NVIDIA",
        "memory_gb": "11 GB",
        "memory_type": "GDDR5X",
        "core_clock": "1480 MHz",
        "boost_clock": "1582 MHz",
        "tdp": "250 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "267 mm",
        "release_date": "2017-03-10",
    },
    {
        "name": "AMD Radeon RX 580",
        "manufacturer": "AMD",
        "memory_gb": "8 GB",
        "memory_type": "GDDR5",
        "core_clock": "1257 MHz",
        "boost_clock": "1340 MHz",
        "tdp": "185 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "256 mm",
        "release_date": "2017-04-18",
    },
    {
        "name": "NVIDIA Quadro RTX 6000",
        "manufacturer": "NVIDIA",
        "memory_gb": "24 GB",
        "memory_type": "GDDR6",
        "core_clock": "1440 MHz",
        "boost_clock": "1770 MHz",
        "tdp": "260 W",
        "interface": "PCIe 3.0 x16",
        "length_mm": "267 mm",
        "release_date": "2018-08-13",
    },
    {
        "name": "AMD Radeon Pro W6800",
        "manufacturer": "AMD",
        "memory_gb": "32 GB",
        "memory_type": "GDDR6",
        "core_clock": "1979 MHz",
        "boost_clock": "2320 MHz",
        "tdp": "250 W",
        "interface": "PCIe 4.0 x16",
        "length_mm": "267 mm",
        "release_date": "2021-06-21",
    },
]
